<?php

namespace Database\Seeders;

use App\Models\Book;
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $books = [
            [
                'title' => 'Laravel Up & Running',
                'writer' => 'Mr.Lorem',
                'publisher' => 'O\'Reilly Media',
                'ISBN' => 9781492041212,
                'publication_year' => '2019',
                'book_spine_number' => '001',
                'page_size' => 400,
                'information' => 'Comprehensive guide to Laravel.',
                'image' => 'laravel_up_and_running.jpg',
                'stock' => 10,
                'rack_id' => 1,
            ],
            [
                'title' => 'Mastering Laravel',
                'writer' => 'Jane Doe',
                'publisher' => 'Tech Books',
                'ISBN' => 9781492054321,
                'publication_year' => '2020',
                'book_spine_number' => '002',
                'page_size' => 350,
                'information' => 'Advanced techniques in Laravel.',
                'image' => 'mastering_laravel.jpg',
                'stock' => 15,
                'rack_id' => 2,
            ],
            [
                'title' => 'PHP for Beginners',
                'writer' => 'John Smith',
                'publisher' => 'Web Dev Press',
                'ISBN' => 9781492065432,
                'publication_year' => '2018',
                'book_spine_number' => '003',
                'page_size' => 250,
                'information' => 'Introductory guide to PHP.',
                'image' => 'php_for_beginners.jpg',
                'stock' => 8,
                'rack_id' => 3,
            ],
            [
                'title' => 'JavaScript Essentials',
                'writer' => 'Emily Taylor',
                'publisher' => 'JS Books',
                'ISBN' => 9781492076543,
                'publication_year' => '2021',
                'book_spine_number' => '004',
                'page_size' => 300,
                'information' => 'Core concepts of JavaScript.',
                'image' => 'javascript_essentials.jpg',
                'stock' => 12,
                'rack_id' => 4,
            ],
            [
                'title' => 'Vue.js in Action',
                'writer' => 'Michael Brown',
                'publisher' => 'Frontend Masters',
                'ISBN' => 9781492087654,
                'publication_year' => '2021',
                'book_spine_number' => '005',
                'page_size' => 450,
                'information' => 'Hands-on guide to Vue.js.',
                'image' => 'vuejs_in_action.jpg',
                'stock' => 5,
                'rack_id' => 1,
            ],
            [
                'title' => 'React.js Quick Start',
                'writer' => 'Sarah Wilson',
                'publisher' => 'React Press',
                'ISBN' => 9781492098765,
                'publication_year' => '2022',
                'book_spine_number' => '006',
                'page_size' => 320,
                'information' => 'Quick guide to React.js.',
                'image' => 'reactjs_quick_start.jpg',
                'stock' => 20,
                'rack_id' => 2,
            ],
            [
                'title' => 'Advanced Laravel',
                'writer' => 'Mr.Lorem',
                'publisher' => 'Tech Experts',
                'ISBN' => 9781492109876,
                'publication_year' => '2023',
                'book_spine_number' => '007',
                'page_size' => 500,
                'information' => 'Deep dive into Laravel framework.',
                'image' => 'advanced_laravel.jpg',
                'stock' => 7,
                'rack_id' => 3,
            ],
            [
                'title' => 'MySQL Database Design',
                'writer' => 'Alice Johnson',
                'publisher' => 'DB Press',
                'ISBN' => 9781492110987,
                'publication_year' => '2017',
                'book_spine_number' => '008',
                'page_size' => 275,
                'information' => 'Guide to designing MySQL databases.',
                'image' => 'mysql_database_design.jpg',
                'stock' => 9,
                'rack_id' => 4,
            ],
            [
                'title' => 'CSS Mastery',
                'writer' => 'William Roberts',
                'publisher' => 'CSS Press',
                'ISBN' => 9781492121098,
                'publication_year' => '2016',
                'book_spine_number' => '009',
                'page_size' => 360,
                'information' => 'Advanced CSS techniques.',
                'image' => 'css_mastery.jpg',
                'stock' => 10,
                'rack_id' => 1,
            ],
            [
                'title' => 'HTML5 & CSS3 for Dummies',
                'writer' => 'George Lee',
                'publisher' => 'Web Dev Books',
                'ISBN' => 9781492132109,
                'publication_year' => '2015',
                'book_spine_number' => '010',
                'page_size' => 410,
                'information' => 'Beginner\'s guide to HTML5 & CSS3.',
                'image' => 'html5_css3_for_dummies.jpg',
                'stock' => 6,
                'rack_id' => 2,
            ],
            [
                'title' => 'Laravel Testing Decoded',
                'writer' => 'Chris Smith',
                'publisher' => 'Laravel Press',
                'ISBN' => 9781492143210,
                'publication_year' => '2020',
                'book_spine_number' => '011',
                'page_size' => 340,
                'information' => 'Testing strategies in Laravel.',
                'image' => 'laravel_testing_decoded.jpg',
                'stock' => 18,
                'rack_id' => 3,
            ],
            [
                'title' => 'Web Development with Vue.js',
                'writer' => 'Rachel Adams',
                'publisher' => 'Vue.js Books',
                'ISBN' => 9781492154321,
                'publication_year' => '2019',
                'book_spine_number' => '012',
                'page_size' => 380,
                'information' => 'Comprehensive guide to web development with Vue.js.',
                'image' => 'web_dev_vuejs.jpg',
                'stock' => 14,
                'rack_id' => 4,
            ],
        ];

        foreach ($books as $book) {
            Book::create([
                'title' => $book['title'],
                'slug' => Str::slug($book['title']),
                'writer' => $book['writer'],
                'publisher' => $book['publisher'],
                'ISBN' => $book['ISBN'],
                'publication_year' => $book['publication_year'],
                'book_spine_number' => $book['book_spine_number'],
                'page_size' => $book['page_size'],
                'information' => $book['information'],
                'image' => $book['image'],
                'stock' => $book['stock'],
                'rack_id' => $book['rack_id'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
